```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r enhanced_backend/requirements.txt
    
    - name: Test backend health
      run: |
        cd enhanced_backend
        python -c "from simple_main import app; print('Backend imports successfully')"

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: enhanced_frontend/yarn.lock
    
    - name: Install dependencies
      run: |
        cd enhanced_frontend
        yarn install --frozen-lockfile
    
    - name: Build frontend
      run: |
        cd enhanced_frontend
        yarn build
    
    - name: Test frontend
      run: |
        cd enhanced_frontend
        yarn test --coverage --watchAll=false

  docker-build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker build -t claude-engineer-enhanced .
    
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container claude-engineer-enhanced
        sleep 30
        docker logs test-container
        docker stop test-container

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
```
